#Configure GraphQL 
graphql:
  tools:
    schemaLocationPattern: "**/*.graphql"
  servlet:
    mapping: /graphql
    enabled: true
  
## JPA Database Configuration 
spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop  
      spring:
        
## H2 & Data Source Configuration  
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE 
    
## Gerneral Spring Configuration 
server:
  port: 4000
  
